### ISSUE TITLE
Support for <3.9

### ISSUE THREAD

**Issue by ammaraslamtk** [TrueLayer/truelayer-signing#131]
## Motivations

The library needs to be force installed with "pip install truelayer_signing --ignore-requires-python", it seems to work fine with python 3.8

## Solution

The library shouldn't limit itself to 3.9 and 3.10 if it works with other versions, or conditions should be added to have a broader support 

## Alternatives

N/A

## Additional context

N/A

**Comment by tl-flavio-barinas** [comment]
Added support for python 3.8
Not going to support python 3.7 as EOS is 2023-06-27
