### ISSUE TITLE
Unable to Verify Signature

### ISSUE THREAD

**Issue by fernandoc4f** [TrueLayer/truelayer-signing#187]
## Bug description

Unable to Verify Signature

## To Reproduce

I am using the [TrueLayer CLI](https://docs.truelayer.com/docs/develop-and-test-a-webhook-endpoint-locally#using-the-source) to send Webhooks and all works as expected, but when I the webhook arrives to my `/payment-status` path and try to verify the signature it thows an Error `[SignatureError]: Invalid signature`

Doing the payment manually throws the same error

```typescript
 async function verify(headers: object, body: object) {
    try {
      const tlSignature = headers as TrueLayerVerifySignatureProps;
      const webhookSignature = tlSignature["tl-signature"];

      const jku = tlSigning.extractJku(webhookSignature);

      if (!jku) throw new Error("No webhooks.truelayer.com found");

      const jwks = await fetch(jku);
      const jwksJSON = await jwks.json();

      tlSigning.verify({
        jwks: JSON.stringify(jwksJSON),
        signature: webhookSignature,
        method: tlSigning.HttpMethod.Post,
        path: "/payments",
        body: JSON.stringify(body),
        headers: headers as Record<string, string>,
      });
    } catch (err) {
      console.error(err);
    }
  }
```
I am following the steps shown [here](https://github.com/TrueLayer/truelayer-signing/tree/main/nodejs#verifying-webhooks) 

## Expected behavior

Verified signature

## Environment

MacOS
Node 18
Typescript 5
truelayer-signing: "^0.1.7"
Rust 1.70.0

**Comment by fernandoc4f** [comment]
I also tried to verify the signature using the npm jsonwebtoken and the jwt-to-pem packages but I get the same error, seems that the Public Key that I get is wrong

**Comment by kplattret** [comment]
Hi there. I think using the CLI might change the path somewhere in the process, which means that the path used for signing isn't the same as the one used for verifying. I would recommend testing signature verification without the CLI, maybe using our sandbox environment.

**Comment by kplattret** [comment]
@fernandoc4f without any reply from you, I'll assume this is now working fine and I'll close this issue. Please feel free to reopen if you're still having trouble.
