### ISSUE TITLE
Can someone help?

### ISSUE THREAD

**Issue by roja300** [TrueLayer/truelayer-signing#201]
I have no idea where I am going wrong so forgive me for posting this here as this probably isn't a bug. 

I just wondered why this isn't working? 

`
public async Task<ActionResult> AuthenticatePayement(string accessToken)
{
    TrueLayerPaymentRequest trueLayerPaymentRequest = new TrueLayerPaymentRequest();

    Guid randomGuid = Guid.NewGuid(); //change this
    trueLayerPaymentRequest.SetDefault();
    trueLayerPaymentRequest.AccessToken = accessToken;

    string requestBody = trueLayerPaymentRequest.ToJson();

    var tlSignature = Signer.SignWithPem(TrueLayerConfig.KeyId, TrueLayerConfig.PrivKeyPem)
        .Method("POST")
        .Path("/payments")
        .Header("Idempotency-Key", randomGuid.ToString())
        .Header("Authorization", $"Bearer {accessToken}")
        .Body(requestBody)
        .Sign();

    var request = new HttpRequestMessage(HttpMethod.Post, "https://api.truelayer-sandbox.com/v3/payments");
    // Request body & any signed headers *must* exactly match what was used to generate the signature.
    request.Content = new StringContent(requestBody, Encoding.UTF8, "application/json");
    request.Headers.Add("Idempotency-Key", randomGuid.ToString());
    request.Headers.Add("Authorization", $"Bearer {accessToken}");
    request.Headers.Add("Tl-Signature", tlSignature);

    var response = new HttpClient().Send(request); 

    return Ok(response);
} 
`

I get a 204 response code when testing the signature but here it just doesn't work. I think it's something to do with the fact that the number of bytes may change when I set the request.Content and turn the requestBody into a StringContent obj.

Any help would be greatly appreciated.

**Comment by Mearman** [comment]
You need the version prefix
```
.Path("/v3/payments")
 ```

**Comment by kplattret** [comment]
@roja300 are you still having trouble with this at all? If not then I'll close the issue at the end of the month.
