### ISSUE TITLE
Verifying Signature

### ISSUE THREAD

**Issue by BRadHoc** [TrueLayer/truelayer-signing#33]
I've created the signature and I'm sending it over but it's saying it's invalid.

I've tried to verify the signature using the function example you provided however I'm unsure about some of the variables, namely does `Idempotency-Key` need to be the same as the one used to create the signature and what should `Correlation-Id` be? The signature?

Also do you replace `User-Agent`?

Hope you are having a fantastic holiday & you and your family are keeping safe!

**Comment by alexheretic** [comment]
Hello! The signing libs will create a signature for `method + path + body + headers`, the verifier will ensure these match.

So when sending you must ensure everything you passed to the signer matches exactly the actual request. In particular that the body is exactly the same bytes.

For verifying it simply needs to be fed the info it received along with the signature and it can use the public key to verify. You can add all headers received to the verifier, though it only needs the headers that were actually signed (not all header are required to be signed, only particular ones).

> namely does `Idempotency-Key` need to be the same as the one used to create the signature and what should `Correlation-Id` be? The signature?

So yes you must send the headers you sign, and to verify them they must be passed to the verifier _(note: you don't generally need to care about verifying as a sender)_. I believe `Correlation-Id` was just used as an example of a header. There are no special headers for signing, required headers will be described in the individual resource documentation.

Hope that helps! If not, can you describe your usage in more detail?

**Comment by alexheretic** [comment]
I'll close this for now. We can of course re-open with more info.
