### ISSUE TITLE
Release of the Go package

### ISSUE THREAD

**Issue by jeynesrya** [TrueLayer/truelayer-signing#40]
This isn't strictly a bug but I didn't know where else to post this - would it be possible to get a release of Go package which is labelled as `0.1.3` in  the `CHANGELOG.md`? There is a bugfix in the main branch (#37) which will help resolve some issues I'm experiencing with the library at the moment.

Cheers!

**Comment by tl-marco-tormento** [comment]
Sorry about that, I forgot to tag the release.
Should be ok now!
